version: '3'

services:
  cpielasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: cpielasticsearch
    command: >
      /bin/sh -c "./bin/elasticsearch-plugin list | grep -q ingest-attachment 
      || yes | ./bin/elasticsearch-plugin install --silent ingest-attachment; 
      /usr/local/bin/docker-entrypoint.sh eswrapper" 
    #entrypoint: ["sh", "/apps/docker-entrypoint-es-plugins.sh"]
    environment:
      - node.name=cpielasticsearch
      - discovery.seed_hosts=cpielasticsearch
      - cluster.initial_master_nodes=cpielasticsearch
      - cluster.name=cpidocker-cluster
      - bootstrap.memory_lock=true
      - xpack.ml.enabled=false
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      #- xpack.security.enabled=true
      #- ELASTIC_PASSWORD="udel1234"
      - http.port=9201-9301
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - cpidata:/usr/share/elasticsearch/data
      - .:/apps
    ports:
      - 9201:9201

  cpikibana:
    image: docker.elastic.co/kibana/kibana:7.17.9
    container_name: cpikibana
    environment:
      ELASTICSEARCH_HOSTS: "http://cpielasticsearch:9201"
      SERVER_BASEPATH: /cpi-kibana
      SERVER_PUBLICBASEURL: https://infolab.ece.udel.edu/cpi-kibana
      SERVER_REWRITEBASEPATH: 'true'
    ports:
      - 5602:5601
    depends_on:
      - cpielasticsearch

  cpiweb:
    build: ./web
    restart: always
    container_name: cpiweb
    ports:
      - 5001:5001
    environment:
      PYTHONUNBUFFERED: 0
      ELASTICSEARCH_URL: "http://cpielasticsearch:9201"
    depends_on:
      - cpielasticsearch
    volumes:
      - ./web:/app

volumes:
  cpidata:
    driver: local


#xpack.security.enabled: true
#xpack.security.transport.ssl.enabled: true